from graphviz import Graph

g = Graph('G', filename='undirected_graphs', engine='dot')

g.edge('Вiльнюс',         'Брест',           label='531',  weight='531')
g.edge('Вiтебськ',        'Брест',           label='638',  weight='638')
g.edge('Вiтебськ',        'Вiльнюс',         label='360',  weight='360')
g.edge('Воронiж',         'Вiтебськ',        label='869',  weight='869')
g.edge('Воронiж',         'Волгоград',       label='581',  weight='581')
g.edge('Волгоград',       'Вiтебськ',        label='1455', weight='1455')
g.edge('Вiтебськ',        'Нижнiй Новгород', label='911',  weight='911')
g.edge('Вiльнюс',         'Даугавпілс',      label='211',  weight='211')
g.edge('Калiнiнград',     'Брест',           label='699',  weight='699')
g.edge('Калiнiнград',     'Вiльнюс',         label='333',  weight='333')
g.edge('Каунас',          'Вiльнюс',         label='102',  weight='102')
g.edge('Київ',            'Вiльнюс',         label='734',  weight='734')
g.edge('Київ',            'Житомир',         label='131',  weight='131')
g.edge('Житомир',         'Донецьк',         label='863',  weight='863')
g.edge('Житомир',         'Волгоград',       label='1493', weight='1493')
g.edge('Кишинiв',         'Київ',            label='467',  weight='467')
g.edge('Кишинiв',         'Донецьк',         label='812',  weight='812')
g.edge('Санкт-Петербург', 'Вiтебськ',        label='602',  weight='602')
g.edge('Санкт-Петербург', 'Калiнiнград',     label='739',  weight='739')
g.edge('Санкт-Петербург', 'Рига',            label='641',  weight='641')
g.edge('Москва',          'Казань',          label='815',  weight='815')
g.edge('Москва',          'Нижнiй Новгород', label='411',  weight='411')
g.edge('Москва',          'Мiнськ',          label='690',  weight='690')
g.edge('Москва',          'Донецьк',         label='1084', weight='1084')
g.edge('Москва',          'Санкт-Петербург', label='664',  weight='664')
g.edge('Мурманськ',       'Санкт-Петербург', label='1412', weight='1412')
g.edge('Мурманськ',       'Мiнськ',          label='2238', weight='2238')
g.edge('Орел',            'Вiтебськ',        label='522',  weight='522')
g.edge('Орел',            'Донецьк',         label='709',  weight='709')
g.edge('Орел',            'Москва',          label='368',  weight='368')
g.edge('Одеса',           'Київ',            label='487',  weight='487')
g.edge('Рига',            'Каунас',          label='267',  weight='267')
g.edge('Таллін',          'Рига',            label='308',  weight='308')
g.edge('Харків',          'Київ',            label='471',  weight='471')
g.edge('Харків',          'Сімферополь',     label='639',  weight='639')
g.edge('Ярославль',       'Воронiж',         label='739',  weight='739')
g.edge('Ярославль',       'Мiнськ',          label='940',  weight='940')
g.edge('Уфа',             'Казань',          label='525',  weight='525')
g.edge('Уфа',             'Самара',          label='461',  weight='461')
g.view()
